server:
   port: 8761

spring:
  application:
     name: eurekaServer

eureka:
   client:
      registerWithEureka: false
      fetchRegistry: false
      service-url:
          defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
